version: "3.8"
services:
  rebelsai:
    container_name: "rebelsai"
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
      - ../../rebelsai-data:/data
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - rebelsai-postgres-db

  rebelsai-postgres-db:
    container_name: "rebelsai-postgres-db"
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - rebelsai_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rebelsai
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbrebelsai
  
volumes:
  rebelsai_postgres_data: